package cn.pacificimmi.common;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import cn.pacificimmi.common.models.base.BaseDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictionary extends BaseDictionary<Dictionary>{
	public static final Dictionary dao = new Dictionary();
	private List<Dictionary> subDictionaries = new ArrayList<Dictionary>();
	public List<Dictionary> getSubDictionaries() {
		return subDictionaries;
	}
	
	public void setSubDictionaries(List<Dictionary> subDictionaries) {
		this.subDictionaries = subDictionaries;
	}
	
	public void addDictionary(Dictionary dict){
		subDictionaries.add(dict);
		Collections.sort(subDictionaries, new SortMethod());
	}
	
	class SortMethod implements Comparator<Dictionary>{

		@Override
		public int compare(Dictionary o1, Dictionary o2) {
			  if (o1.getSort() > o2.getSort())
			   return 1;
			return 0;
		}
		
	}
}
