package cn.pacificimmi.common.models;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("console_dictionary", "dict_id", Dictionary.class);
		arp.addMapping("console_operation_log", "id", OperationLog.class);
		arp.addMapping("console_orgnization", "org_id", Orgnization.class);
		// Composite Primary Key order: org_id,sys_id
		arp.addMapping("console_orgnization_websys", "org_id,sys_id", OrgnizationWebsys.class);
		arp.addMapping("console_resource", "res_id", Resource.class);
		arp.addMapping("console_role", "role_id", Role.class);
		// Composite Primary Key order: res_id,role_id
		arp.addMapping("console_role_resource", "res_id,role_id", RoleResource.class);
		// Composite Primary Key order: role_id,station_id
		arp.addMapping("console_role_station", "role_id,station_id", RoleStation.class);
		arp.addMapping("console_station", "station_id", Station.class);
		arp.addMapping("console_user", "user_id", User.class);
		// Composite Primary Key order: station_id,user_id
		arp.addMapping("console_user_station", "station_id,user_id", UserStation.class);
		arp.addMapping("console_websys", "sys_id", Websys.class);
		arp.addMapping("crm_activity", "activity_id", Activity.class);
		arp.addMapping("crm_activity_sign", "sign_id", ActivitySign.class);
		arp.addMapping("crm_address_city", "CityId", City.class);
		arp.addMapping("crm_address_country", "CountryId", Country.class);
		arp.addMapping("crm_address_province", "ProvinceId", Province.class);
		arp.addMapping("crm_business_cooperation", "id", BusinessCooperation.class);
		arp.addMapping("crm_business_negotiation", "id", BusinessNegotiation.class);
		arp.addMapping("crm_city", "id", City.class);
		arp.addMapping("crm_custinfo", "custinfo_id", Custinfo.class);
		arp.addMapping("crm_custinfo_feedback", "custinfo_feedback_id", CustinfoFeedback.class);
		arp.addMapping("crm_immigration_policy", "id", ImmigrationPolicy.class);
		arp.addMapping("crm_information_article", "info_id", InformationArticle.class);
		arp.addMapping("crm_information_img", "info_id", InformationImg.class);
		arp.addMapping("crm_message", "msg_id", Message.class);
		arp.addMapping("crm_project_expands", "project_expands_id", ProjectExpands.class);
		arp.addMapping("crm_project_resource", "project_resource_id", ProjectResource.class);
		arp.addMapping("crm_proxy_status_record", "proxy_status_record_id", ProxyStatusRecord.class);
		arp.addMapping("crm_section", "section_id", Section.class);
		arp.addMapping("crm_steward_like", "like_id", StewardLike.class);
		arp.addMapping("crm_steward_sign", "sign_id", StewardSign.class);
		arp.addMapping("crm_steward_user", "steward_id", StewardUser.class);
		arp.addMapping("portal_channel", "channel_id", PortalChannel.class);
		arp.addMapping("portal_invitation_code", "id", PortalInvitationCode.class);
		arp.addMapping("portal_live", "live_id", PortalLive.class);
		arp.addMapping("portal_live_application", "application_id", PortalLiveApplication.class);
		arp.addMapping("portal_live_like", "id", PortalLiveLike.class);
		arp.addMapping("portal_live_message", "message_id", PortalLiveMessage.class);
		arp.addMapping("wx_estimate_question_version", "version_id", WxEstimateQuestionVersion.class);
		arp.addMapping("wx_estimate_record", "estimate_record_id", WxEstimateRecord.class);
		arp.addMapping("wx_estimatet_detail_record", "estimate_detail_record_id", WxEstimatetDetailRecord.class);
	}
}

