package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BasePortalLiveLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortalLiveLike extends BasePortalLiveLike<PortalLiveLike> {
	public static final PortalLiveLike dao = new PortalLiveLike();
}
