package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BasePortalChannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortalChannel extends BasePortalChannel<PortalChannel> {
	public static final PortalChannel dao = new PortalChannel();
}
