package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BasePortalLiveMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortalLiveMessage extends BasePortalLiveMessage<PortalLiveMessage> {
	public static final PortalLiveMessage dao = new PortalLiveMessage();
}
