package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BasePortalLiveApplication;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortalLiveApplication extends BasePortalLiveApplication<PortalLiveApplication> {
	public static final PortalLiveApplication dao = new PortalLiveApplication();
}
