package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BasePortalInvitationCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortalInvitationCode extends BasePortalInvitationCode<PortalInvitationCode> {
	public static final PortalInvitationCode dao = new PortalInvitationCode();
}
