package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BasePortalLive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PortalLive extends BasePortalLive<PortalLive> {
	public static final PortalLive dao = new PortalLive();
}
