package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Province extends BaseProvince<Province> {
	public static final Province dao = new Province();
}
