package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWxEstimateRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxEstimateRecord extends BaseWxEstimateRecord<WxEstimateRecord> {
	public static final WxEstimateRecord dao = new WxEstimateRecord();
}
