package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWxEstimateQuestionVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxEstimateQuestionVersion extends BaseWxEstimateQuestionVersion<WxEstimateQuestionVersion> {
	public static final WxEstimateQuestionVersion dao = new WxEstimateQuestionVersion();
}
