package cn.pacificimmi.common.models;

import cn.pacificimmi.common.models.base.BaseWxEstimatetDetailRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxEstimatetDetailRecord extends BaseWxEstimatetDetailRecord<WxEstimatetDetailRecord> {
	public static final WxEstimatetDetailRecord dao = new WxEstimatetDetailRecord();
}
