package cn.pacificimmi.common.models.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTopics<M extends BaseTopics<M>> extends Model<M> implements IBean {

	public void setTopicId(java.lang.Integer topicId) {
		set("topic_id", topicId);
	}

	public java.lang.Integer getTopicId() {
		return get("topic_id");
	}

	public void setTopicName(java.lang.String topicName) {
		set("topic_name", topicName);
	}

	public java.lang.String getTopicName() {
		return get("topic_name");
	}

	public void setTopicMark(java.lang.String topicMark) {
		set("topic_mark", topicMark);
	}

	public java.lang.String getTopicMark() {
		return get("topic_mark");
	}

	public void setTopicSort(java.lang.Integer topicSort) {
		set("topic_sort", topicSort);
	}

	public java.lang.Integer getTopicSort() {
		return get("topic_sort");
	}

	public void setTopicImage(java.lang.String topicImage) {
		set("topic_image", topicImage);
	}

	public java.lang.String getTopicImage() {
		return get("topic_image");
	}

	public void setTopicUrl(java.lang.String topicUrl) {
		set("topic_url", topicUrl);
	}

	public java.lang.String getTopicUrl() {
		return get("topic_url");
	}

	public void setSeoKeywords(java.lang.String seoKeywords) {
		set("seo_keywords", seoKeywords);
	}

	public java.lang.String getSeoKeywords() {
		return get("seo_keywords");
	}

	public void setSeoMark(java.lang.String seoMark) {
		set("seo_mark", seoMark);
	}

	public java.lang.String getSeoMark() {
		return get("seo_mark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setDeleteFlag(java.lang.String deleteFlag) {
		set("delete_flag", deleteFlag);
	}

	public java.lang.String getDeleteFlag() {
		return get("delete_flag");
	}

	public void setTopicStatus(java.lang.String topicStatus) {
		set("topic_status", topicStatus);
	}

	public java.lang.String getTopicStatus() {
		return get("topic_status");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("update_time");
	}

	public void setEditUser(java.lang.String editUser) {
		set("edit_user", editUser);
	}

	public java.lang.String getEditUser() {
		return get("edit_user");
	}

}
